language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
 - OCAML_VERSION=4.02
 - OCAML_VERSION=latest
os:
 - linux
 - osx

# language: c
# sudo: required
# script: bash -ex .travis-ci.sh
